In [18]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from importlib import reload
from pathlib import Path

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [19]:
# from sleeper.api import LeagueAPIClient
# from sleeper.enum import Sport
# from sleeper.model import League, Roster, User, Matchup, PlayoffMatchup, Transaction, TradedPick, SportState
# # usfl_2022: League = LeagueAPIClient.get_league(league_id='786691248676257792')
# elite_2021: League = LeagueAPIClient.get_league(league_id='736885905629024256')

In [32]:
import ff_league_analyzer.ff_league_analyzer
# from ff_league_analyzer import SleeperLeague
# from ff_league_analyzer import SleeperLeagueAnalyzer
# importlib.reload(ff_league)
reload(ff_league_analyzer)
from ff_league_analyzer import ff_league
from ff_league import SleeperLeague
from ff_league_analyzer.ff_league_analyzer import SleeperLeagueAnalyzer
# reload(ff_league_analyzer.ff_league_analyzer.SleeperLeague)

In [33]:
usfl_2022 = SleeperLeague(league_id='786691248676257792')
# usfl_2022_analyzer = SleeperLeagueAnalyzer(league_id='786691248676257792')

In [34]:
usfl_2022.get_data('league')

Get Leauge

{1: 11}

In [11]:
users = usfl_2022_analyzer.df_users
teams = usfl_2022_analyzer.df_teams
print(users.columns)
print(teams.columns)

Index(['user_id', 'team_name', 'display_name', 'is_commish'], dtype='object')
Index(['owner_id', 'roster_id', 'division', 'wins', 'losses', 'ties', 'points_for', 'points_against', 'possible_points', 'record', 'rostered', 'starters', 'bench', 'ir', 'taxi', 'roster_locked'], dtype='object')

In [17]:
(
    teams
    .merge(users.rename(columns={'user_id': 'owner_id'}), on='owner_id', how='left')
    [['team_name', 'display_name', 'wins', 'losses', 'ties', 'points_for', 'points_against', 'rostered']]
    .sort_values(['points_for', 'points_against'])
)

                    team_name   display_name wins losses ties  points_for  points_against  rostered
0             Boston Breakers     GermyBeast    0      0    0         0.0             0.0        43
1           Tampa Bay Bandits     emerald247    0      0    0         0.0             0.0        39
2         Los Angeles Express  RedPhoenix437    0      0    0         0.0             0.0        47
3          Jacksonville Bulls       pauly102    0      0    0         0.0             0.0        45
4           Orlando Renegades      Mrhawke19    0      0    0         0.0             0.0        50
5          Pittsburgh Maulers   haydenshaw85    0      0    0         0.0             0.0        45
6           Memphis Showboats         SBB238    0      0    0         0.0             0.0        40
7   Houston Gamblers ♥️♠️♦️♣️      Bolty1028    0      0    0         0.0             0.0        46
8               Detriot Drive      Monty0813    0      0    0         0.0             0.0        40
9        Washington Federals   michaelp42983    0      0    0         0.0             0.0        49
10                  Wranglers      TrizzyTr3    0      0    0         0.0             0.0        45
11          Michigan Panthers      arveatz21    0      0    0         0.0             0.0        43
12           Oakland Invaders   ToximusPrime    0      0    0         0.0             0.0        43
13       Birmingham Stallions       Zach2326    0      0    0         0.0             0.0        46
14               Team skaplan        skaplan    0      0    0         0.0             0.0        45
15         Philadelphia Stars       Curlyz28    0      0    0         0.0             0.0        48
16                Denver Gold   javendano585    0      0    0         0.0             0.0        49
17              Chicago Blitz         Satsin    0      0    0         0.0             0.0        40
18         Team BlakeOtenasek  BlakeOtenasek    0      0    0         0.0             0.0        46
19   San Antonio Gunslingers     mattbanks3x    0      0    0         0.0             0.0        46

In [14]:
# usfl_2022_analyzer.build_rosters_df()
# usfl_2022_analyzer.build_users_df()
usfl_2022_analyzer.get_roster_distribution()

                    team_name record  QB  RB  WR  TE  K  DL  DL/LB  LB  DB
0    San Antonio Gunslingers   0-0-0   2   9  12   2  2   6      2   5   6
1         Los Angeles Express  0-0-0   5   5   6   6  1   4      3   5  12
2           Memphis Showboats  0-0-0   4   7   6   4  0   3      3   6   7
3          Pittsburgh Maulers  0-0-0   2   3   9   1  1  10      3   3  13
4        Washington Federals   0-0-0   3   6  10   4  2   9      3   4   8
5           Orlando Renegades  0-0-0   3   9  10   4  1   6      4   6   7
6           Tampa Bay Bandits  0-0-0   2   9   5   2  2   5      3   4   7
7        Birmingham Stallions  0-0-0   3   8   6   6  3   4      2   5   7
8                Team skaplan  0-0-0   4   6   6   5  2   5      3   7   7
9   Houston Gamblers ♥️♠️♦️♣️  0-0-0   3   9  11   5  1   4      2   3   7
10         Jacksonville Bulls  0-0-0   4   5   7   2  2   4      5   5  11
11         Philadelphia Stars  0-0-0   2   7   8   2  4   5      2  10   5
12                  Wranglers  0-0-0   3   7  10   1  2   7      1   7   7
13                Denver Gold  0-0-0   3   7   8   3  2   8      1   8   9
14              Detriot Drive  0-0-0   3   5   8   2  1   6      1   3  11
15            Boston Breakers  0-0-0   2   6   8   5  1   1      9   4   7
16           Oakland Invaders  0-0-0   3   3   8   2  1   6      3   4  13
17         Team BlakeOtenasek  0-0-0   4   7   9   8  4   2      2   4   6
18              Chicago Blitz  0-0-0   2   4   7   5  1   7      4   6   4
19          Michigan Panthers  0-0-0   2   6   9   3  1   7      1   7   6